import numpy as np
import os
import cv2

class LUTManager:
    def __init__(self):
        # 支持通道: 'RGB' (全通道同步), 'R', 'G', 'B'
        self.channels = ['RGB', 'R', 'G', 'B']
        self.current_channel = 'RGB'
        
        # 为每个通道维护独立的控制点和 LUT
        self.data = {
            ch: {
                'control_points': [(0, 0), (255, 255)],
                'lut': np.arange(256, dtype=np.uint8)
            } for ch in self.channels
        }
        self.interpolation_mode = 'smooth'
        self.update_all_luts()

    def set_current_channel(self, channel):
        if channel in self.channels:
            self.current_channel = channel

    def get_current_control_points(self):
        return self.data[self.current_channel]['control_points']

    def add_control_point(self, x, y):
        cp = self.data[self.current_channel]['control_points']
        if any(p[0] == x for p in cp):
            return
        cp.append((x, y))
        cp.sort()
        self.update_lut()

    def remove_control_point(self, index):
        cp = self.data[self.current_channel]['control_points']
        if 0 < index < len(cp) - 1:
            cp.pop(index)
            self.update_lut()

    def reset(self):
        """重置当前通道或全通道"""
        if self.current_channel == 'RGB':
            for ch in self.channels:
                self.data[ch]['control_points'] = [(0, 0), (255, 255)]
        else:
            self.data[self.current_channel]['control_points'] = [(0, 0), (255, 255)]
        self.update_all_luts()

    def auto_stretch(self, black_point, white_point):
        """基于黑白场自动对比度拉伸 (仅作用于当前通道)"""
        b = min(black_point, white_point)
        w = max(black_point, white_point)
        if b == w: return
        
        new_cp = [(0, 0), (b, 0), (w, 255), (255, 255)]
        seen = set()
        cleaned_cp = [p for p in new_cp if not (p[0] in seen or seen.add(p[0]))]
        cleaned_cp.sort()
        
        if self.current_channel == 'RGB':
            for ch in self.channels:
                self.data[ch]['control_points'] = list(cleaned_cp)
        else:
            self.data[self.current_channel]['control_points'] = cleaned_cp
            
        self.update_all_luts()

    def update_control_point(self, index, x, y):
        cp = self.data[self.current_channel]['control_points']
        if index == 0: x = 0
        elif index == len(cp) - 1: x = 255
        
        if index > 0: x = max(x, cp[index-1][0] + 1)
        if index < len(cp) - 1: x = min(x, cp[index+1][0] - 1)
            
        cp[index] = (x, np.clip(y, 0, 255))
        self.update_lut()

    def update_lut(self):
        """更新当前通道的 LUT。如果当前是 RGB，则同步更新 R,G,B"""
        self._calculate_lut(self.current_channel)
        if self.current_channel == 'RGB':
            # 同步所有通道
            cp_master = self.data['RGB']['control_points']
            for ch in ['R', 'G', 'B']:
                self.data[ch]['control_points'] = [list(p) for p in cp_master] # 深拷贝
                self.data[ch]['lut'] = self.data['RGB']['lut'].copy()

    def update_all_luts(self):
        for ch in self.channels:
            self._calculate_lut(ch)

    def _calculate_lut(self, channel):
        cp = self.data[channel]['control_points']
        if len(cp) < 2:
            self.data[channel]['lut'] = np.arange(256, dtype=np.uint8)
            return

        x_vals = [p[0] for p in cp]
        y_vals = [p[1] for p in cp]
        
        if self.interpolation_mode == 'smooth' and len(cp) >= 3:
            try:
                from scipy.interpolate import PchipInterpolator
                pchip = PchipInterpolator(x_vals, y_vals)
                self.data[channel]['lut'] = np.clip(pchip(np.arange(256)), 0, 255).astype(np.uint8)
            except ImportError:
                self.data[channel]['lut'] = np.interp(np.arange(256), x_vals, y_vals).astype(np.uint8)
        else:
            self.data[channel]['lut'] = np.interp(np.arange(256), x_vals, y_vals).astype(np.uint8)

    def get_lut(self):
        """返回当前编辑频道的 LUT"""
        return self.data[self.current_channel]['lut']

    def get_multi_channel_lut(self):
        """返回 B, G, R 三通道聚合后的 LUT (用于 cv2.merge 或直接应用到彩色图)"""
        # OpenCV 默认顺序是 BGR
        return np.stack([self.data['B']['lut'], self.data['G']['lut'], self.data['R']['lut']], axis=0)

    def export_lut_adaptive(self, filename, is_color=True, normalize=True):
        """
        导出 .cube 文件
        is_color: True 导出 3 列 (RGB), False 导出 1 列 (Gray)
        normalize: True 映射到 0.0-1.0, False 保留 0-255 整数
        """
        try:
            with open(filename, 'w') as f:
                f.write(f"# Generated by LutTool Professional\n")
                f.write(f"# Mode: {'Color' if is_color else 'Grayscale'}, Scaled: {normalize}\n")
                f.write("LUT_1D_SIZE 256\n")
                
                scale = 255.0 if normalize else 1.0
                fmt = ".6f" if normalize else "d"
                
                for i in range(256):
                    if is_color:
                        r = self.data['R']['lut'][i] / scale
                        g = self.data['G']['lut'][i] / scale
                        b = self.data['B']['lut'][i] / scale
                        if normalize:
                            f.write(f"{r:.6f} {g:.6f} {b:.6f}\n")
                        else:
                            f.write(f"{int(r)} {int(g)} {int(b)}\n")
                    else:
                        # 灰度图，使用 RGB 通道作为 Master
                        v = self.data['RGB']['lut'][i] / scale
                        if normalize:
                            f.write(f"{v:.6f}\n")
                        else:
                            f.write(f"{int(v)}\n")
            return True
        except Exception as e:
            print(f"Export error: {e}")
            return False

    def apply_full_lut_dict(self, lut_dict):
        for ch_key, lut_val in lut_dict.items():
            if ch_key in self.data:
                self.data[ch_key]['lut'] = lut_val.copy()
                new_points = []
                for x in range(256):
                    new_points.append((x, int(lut_val[x])))
                self.data[ch_key]['control_points'] = new_points
        
        if 'RGB' in lut_dict:
            master_lut = lut_dict['RGB']
            master_points = self.data['RGB']['control_points']
            for ch in ['R', 'G', 'B']:
                self.data[ch]['lut'] = master_lut.copy()
                self.data[ch]['control_points'] = [list(p) for p in master_points]
                
        self.update_all_luts()
        return True

    def import_lut(self, filename):
        """导入 .cube 文件，兼容单通道与三通道，精细化拟合 UI"""
        try:
            r_vals, g_vals, b_vals = [], [], []
            with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
                lines = f.readlines()
            
            for line in lines:
                line = line.strip()
                if not line or line.startswith('#') or any(k in line for k in ["LUT_1D_SIZE", "LUT_3D_SIZE", "TITLE", "DOMAIN_MIN", "DOMAIN_MAX"]):
                    continue
                
                parts = line.split()
                if not parts: continue
                
                try:
                    vals = [float(p) for p in parts]
                    # 自动识别量程
                    # 如果任一值 > 1.001 且包含小数点，或者值本来就是 0-255
                    # 我们的策略：如果最大值 <= 1.001，则认为是 0-1.0
                    if len(vals) >= 3:
                        r_vals.append(vals[0])
                        g_vals.append(vals[1])
                        b_vals.append(vals[2])
                    elif len(parts) == 1:
                        r_vals.append(vals[0])
                        g_vals.append(vals[0])
                        b_vals.append(vals[0])
                except ValueError: continue
            
            if not r_vals: return False
            
            # 缩放因子
            max_v = max(max(r_vals), max(g_vals), max(b_vals))
            scale = 255.0 if max_v <= 1.0001 else 1.0
            
            # 使用 numpy 处理缩放
            cur_r = (np.array(r_vals[:256]) * scale).astype(np.uint8)
            cur_g = (np.array(g_vals[:256]) * scale).astype(np.uint8)
            cur_b = (np.array(b_vals[:256]) * scale).astype(np.uint8)
            
            # 更新内部数据
            target_map = {'R': cur_r, 'G': cur_g, 'B': cur_b}
            for ch in ['R', 'G', 'B']:
                if ch in target_map:
                    self.data[ch]['lut'] = target_map[ch]
                    # 精细化拟合控制点 (采样 17 点)
                    new_cp = []
                    samples = np.linspace(0, 255, 17, dtype=int)
                    for sx in samples:
                        new_cp.append((int(sx), int(target_map[ch][sx])))
                    self.data[ch]['control_points'] = new_cp

            # 如果 R,G,B 一致，同步给 RGB Master
            if np.array_equal(cur_r, cur_g) and np.array_equal(cur_g, cur_b):
                self.data['RGB']['lut'] = cur_r.copy()
                self.data['RGB']['control_points'] = [list(p) for p in self.data['R']['control_points']]
            
            self.update_all_luts()
            return True
        except Exception as e:
            print(f"Import error: {e}")
            return False

    def apply_auto_min_max(self, image):
        if image is None: return False
        if len(image.shape) == 3:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY if image.shape[2] == 3 else cv2.COLOR_BGRA2GRAY)
        else:
            gray = image
        black = np.percentile(gray, 1)
        white = np.percentile(gray, 99.5)
        self.auto_stretch(int(black), int(white))
        return True

    def apply_auto_he(self, image):
        if image is None: return False
        if len(image.shape) == 3:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY if image.shape[2] == 3 else cv2.COLOR_BGRA2GRAY)
        else:
            gray = image
        hist, _ = np.histogram(gray.flatten(), 256, [0, 256])
        cdf = hist.cumsum()
        cdf_normalized = (cdf * 255 / cdf[-1]).astype(np.uint8)
        if self.current_channel == 'RGB':
            for ch in self.channels:
                self.data[ch]['lut'] = cdf_normalized.copy()
                self.data[ch]['control_points'] = [(0, int(cdf_normalized[0])), (128, int(cdf_normalized[128])), (255, int(cdf_normalized[255]))]
        else:
            self.data[self.current_channel]['lut'] = cdf_normalized
            self.data[self.current_channel]['control_points'] = [(0, int(cdf_normalized[0])), (128, int(cdf_normalized[128])), (255, int(cdf_normalized[255]))]
        self.update_all_luts()
        return True
